import type { NextPage } from 'next'

import Head from 'next/head';

//import "~/styles/globals.css";  "don't import global css in individual pages"

import Header from "~/components/Header/Header";
import TableOfContent from '~/components/TableOfContent/TableOfContent';
import Projects from '~/components/Project/Projects';
import Introduction from '~/components/Introduction/Introduction';
import Footer from "~/components/Footer/Footer";

import getDarkModeClassName from "darkModeCSS/darkModeClassNames";


const Home: NextPage = () => {

  return (
    <div className={"h-screen w-screen flex flex-col" + getDarkModeClassName("page")}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main id="main" className=" flex flex-row content-height dark:bg-black dark:text-white">
        <div id="main-left" className="hidden md:block flex-1 height-full border-r-2 border-black min-w-0 min-h-0">
          <TableOfContent />
        </div>
        <div id="main-middle" className="flex-none w-screen md:w-3/5 lg:w-2/5 h-full">
          <Projects />
        </div>
        <div id="main-right" className="hidden lg:block flex-1 border-l-2 border-black">
          <Introduction />
        </div>
      </main>
      <Footer />
    </div>
  )
}


export default Home
