import type { NextPage } from 'next'
import { useState, useEffect, useContext } from "react";

import Head from 'next/head';
import Image from 'next/image';
import Link from "next/link";

//import "~/styles/globals.css";  "don't import global css in individual pages"

import Header from "~/components/Header/Header";
import TableOfContent from '~/components/TableOfContent/TableOfContent';
import Projects from '~/components/Project/Projects';
import Introduction from '~/components/Introduction/Introduction';
import Footer from "~/components/Footer/Footer";

//import { DarkModeContext } from "~/pages/_app";
import DarkModeContext from '~/components/contexts/DarkModeContext';


//in next js each page is separate, so I need to put global variables in localStorage to be accessible to every page
const Home: NextPage = () => {
  const darkModeContext = useContext(DarkModeContext);
  const inDarkMode = darkModeContext.inDarkMode;
  const setDarkMode = darkModeContext.setDarkMode;


  return (
    <div className={"h-screen w-screen flex flex-col" + (inDarkMode ? " dark" : "")}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main id="main" className=" flex flex-row content-height">
        <div id="main-left" className="hidden md:block flex-1 height-full border-r-2 border-black min-w-0 min-h-0">
          <TableOfContent />
        </div>
        <div id="main-middle" className="flex-none w-screen md:w-3/5 lg:w-2/5 h-full">
          <Projects />
        </div>
        <div id="main-right" className="hidden lg:block flex-1 border-l-2 border-black">
          <Introduction />
        </div>
      </main>
      <Footer />
    </div>
  )
}


export default Home
